version: '3.9'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: plupp-admin
      MONGO_INITDB_ROOT_PASSWORD: gott-mos
      MONGO_INITDB_DATABASE: plupp-calendar
    volumes:
      - db_data:/data/db
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - '4444:27017'
volumes:
  db_data:
